id: IFB91751E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:30:47+00:00'
last_modified: '2022-06-08T05:16:42.046985+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG02677
  title: ཡིད་བཞིན་མཛོད་ཀྱི་འགྲེལ་པ་པདྨ་དཀར་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E554:
      image_group_id: I00KG02990
      title: Volume 1 of yid bzhin mdzod kyi 'grel pa
      total_pages: 570
      order: 1
      base_file: E554.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
